---
abstract: 'MongoDB Backend using Meerkat for Deeme'
author:
  - 'mudler <mudler@dark-lab.net>'
build_requires:
  MongoDB::Connection: 0
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.035
  perl: 5.008005
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Deeme-Backend-Meerkat
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Deeme: 0
  Deeme::Utils: 0
  Meerkat: 0
  Meerkat::Role::Document: 0
  Mojo::Base: 0
  Moose: 0
resources:
  bugtracker: https://github.com/mudler/p5-Deeme-Backend-Meerkat/issues
  homepage: https://github.com/mudler/p5-Deeme-Backend-Meerkat
  repository: https://github.com/mudler/p5-Deeme-Backend-Meerkat.git
version: 0.01
